name: Python safety check

on: [push]
 

env:
  DEP_PATH: requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main
        uses: actions/checkout@v2

      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check